name: build and deploy v1

on:
  push:
    branches:
      - v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          REACT_APP_GIT_SHA: ${{ github.sha }}

      - name: Test
        run: yarn test

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && secrets.REGISTRY_SEED_V1 || '' }}
